version: '3'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/root/.influxdbv2
    restart: always
volumes:
  influxdb_data:
